### PR TITLE
Re-release v0.10.12

### PR DESCRIPTION
**Pull request by Chochek**
With two bug fixes:
- [x] [#102984316] Fix dynamic row height
- [x] [#102913762] Move min-width from table header cell to table data cell

### CODE REVIEW

**Comment by Chochek** [comment]
### Review plan
- [ ] `components/ga-tables.min.js`is updated
- [ ] `ga-conventions.css`is updated
- [ ] `ga-conventions.min.js`is updated
- [ ] `styles/_tables.scss`is updated

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan
- [ ] https://github.com/GetAmbassador/conventions-bower/releases/tag/v0.10.12 release time is a few minutes ago (4 at the time of this comment)
- [ ] https://github.com/GetAmbassador/ambassador-conventions/releases/tag/v0.10.12 release time is 3 hours ago

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
