### PR TITLE
Release v0.11.10

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Fixed row selecting on smart tables

### CODE REVIEW

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/5174e725fdda49c761af6e087bcda7f8be676d21/bower.json#L3) has updated version v0.11.10

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.10
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.10
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.10

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
