### PR TITLE
Release v0.4.24

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Ability to pass custom true and false values into ga-form-field checkboxes
- [x] Fix loader overlay occasionally showing without the spinner in ga-loader

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/b8332e3789f49d38b32be6b67bf10bdd89c5754b/bower.json#L3) is updated to v0.4.24

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.24
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.24
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.24

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:palm_tree:

**Pull request merged**
