### PR TITLE
Re-Release v0.7.0

### PR DESCRIPTION
**Pull request by tplorts**

### CODE REVIEW

**Comment by tplorts** [comment]
### Review Plan 
- [ ] Go to [this file](https://github.com/GetAmbassador/conventions-bower/blob/8d11c3cc2fb08080115a4a1dc2b3df42897d1a24/ga-conventions.min.js) and search for `_.union`. It should exist once in the file now.

**Comment by tplorts** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by tplorts** [comment]
### QA Plan

- [ ] conventions-bower 0.7.0 release date is today https://github.com/GetAmbassador/conventions-bower/releases
- [ ] ambassador-conventions 0.7.0 release date is today https://github.com/GetAmbassador/ambassador-conventions/releases

**Comment by tplorts** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
