### PR TITLE
Release v0.4.15

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Fix table flashing when search is saved
- [x] Fix donut chart showing null when all values are 0

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/75447a77637a44e1485ffa5efd0b82a1f5d07d24/bower.json#L3) is updated to v0.4.15

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.15
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.15
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.15

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:palm_tree:

**Pull request merged**
