### PR TITLE
Release v0.7.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [ ] Search results in order
- [ ] Little region at left of check box field is deceptively not clickable
- [ ] Add maxWidth param to smartTable columns

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/f29af9d380c292eb0cdfcd725b2cb2f165196894/bower.json#L3) is updated to v0.7.2

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
## QA Plan

- [x] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.7.2
- [x] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.7.2
- [x] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.7.2

**Comment by Chochek** [comment]
@tplorts please QA

**Comment by tplorts** [comment]
QAing

**Comment by tplorts** [comment]
:white_square_button: :palm_tree: :white_square_button: 
:palm_tree: :white_check_mark:  :palm_tree:
:white_square_button: :palm_tree: :white_square_button:

**Pull request merged**
