### PR TITLE
Re-Release v0.9.1

### PR DESCRIPTION
**Pull request by Chochek**
CSS wasn't pulled into master on conventions :/

### CODE REVIEW

**Comment by Chochek** [comment]
### Review plan
- [ ] `ga-conventions.css` and `styles/_modals.scss` are updated

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
This will be QA'd through #84 because I didn't create releases here and in conventions before I merged this
@gpszymczak please give it a :palm_tree: if #84 gets one :)

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
