### PR TITLE
Release v0.10.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain
- [x] Update snippet form styles
- [x] Add option to auto-extend textarea fields
- [x] Add radio to validated form fields
- [x] Add validated redactor editor
- [x] Add border radius to the img element in ga-avatar
- [x] Upgrade angular-toggle-switch to 0.5.2 where disabling functionality is fixed

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/f14439300882a13283631ecec9680ca0bbb18d98/bower.json#L3) has updated version v0.10.2
- [ ] Dependencies are also updated:
  - [ ] "angular-bootstrap": "0.11.0"
  - [ ] "angular-bootstrap-colorpicker": "3.0.9"
  - [ ] "zeroclipboard": "2.1.6"
  - [ ] "ng-clip": "0.2.4"
  - [ ] "angular-bootstrap-toggle-switch": "0.5.4"
  - [ ] "angular-animate": "1.2.16"
  - [ ] "autosize": "~3.0.6"

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.2

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
