### PR TITLE
Release v0.9.3

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain:
- [x] - Keep selected dropdown item in view when arrowing up/down
- [x] - Rename `title` attribute on gaModal 
- [x] - Make sure that buttons have the same text and spinner color
- [x] - Add proxima-nova-semibold

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/2fad6d1447690847321088d9f28ae6441e3803c2/bower.json#L3) is updated to v0.9.3
- [ ] [Proxima Nova folder] (https://github.com/GetAmbassador/conventions-bower/tree/87_release_v0_9_3/fonts/proxima-nova) contains the Proxima Nova Semibold font files

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.9.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.9.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.9.3
- [ ] [Proxima Nova folder] (https://github.com/GetAmbassador/conventions-bower/tree/master/fonts/proxima-nova) contains the Proxima Nova Semibold font files

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
