### PR TITLE
Release v0.10.9

### PR DESCRIPTION
**Pull request by Chochek**
This release includes:
- [x] Changed all instances of NODE_ENV to CONVENTIONS_ENV
- [x] Add option to place the table search field either left or right
- [x] Add option to display apply actions as buttons above the table when rows are selected

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/ad049b0c85a4fa4ed7c266d4f7bee6f0fa2a6ade/bower.json#L3) has updated version v0.10.9

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.9
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.9
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.9

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
