### PR TITLE
Release v0.4.20

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:

- [x] Calculate activity feed time based on GMT vs browser timezone
- [x] Ability to pass a custom result classes into the select directive
- [x] Added option on ga-select to allow model to be set as the pasted input value

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated 
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/71b83a0facdb3a3490eaf8ff673d71bb8de7942d/bower.json#L3) is updated to 0.4.20

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.20
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.20
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.20

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:palm_tree:

**Pull request merged**
