### PR TITLE
Release v0.6.4

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:

- [ ] Fixed: gaSlider not working without jQuery
- [ ] Fixed: $script.load duplicate prevention causes premature executions

### CODE REVIEW

**Comment by jivinivan** [comment]
Moved to todo since we discussed offline and it's important.

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated 
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/19795d371b3282726a72b2813be8e94b9d97acb6/bower.json#L3) is updated to 0.6.4

**Comment by jivinivan** [comment]
@tplorts please review

**Comment by tplorts** [comment]
reviewing

**Comment by tplorts** [comment]
:+1:

**Comment by jivinivan** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.6.4
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.6.4
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.6.4

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:palm_tree:

**Pull request merged**
