### PR TITLE
Release v0.11.5

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- [x] Added tooltip option to header cells

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/7e863bd72143cf292989db15aa3d4666489fc415/bower.json#L3) has updated version v0.11.5

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.5
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.5
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.5

**Comment by jivinivan** [comment]
@briandavidson please QA

**Comment by briandavidson** [comment]
QA'ing

**Comment by briandavidson** [comment]
:moneybag:

**Pull request merged**
