### PR TITLE
Release v0.11.1

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- Table will now broadcast an event when data has finished loading
- Table action dropdown improvements on small screens
- Updated radio button design
- Added plus icon/add button to the manual-entry ga-select

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/cd4f0894b4883f73b231d35994c5d52b6366ac20/bower.json#L3) has updated version v0.11.1

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.1

**Comment by jivinivan** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
