### PR TITLE
Release v0.8.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will include
- [x] Fix async typeahead filtering
- [x] proxima nova thin
- [x] Implement the new modal design
- [x] Implement the new alerts design
- [x] New stats circles
- [x] New style options for selects/typeaheads
- [x] New button style options
- [x] Upgrade Fontawesome
- [x] Add a dynamicTooltip directive

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/61ffbb32a5c6f75a8d61f6f059fc9b39cfd7e5e7/bower.json#L3) is updated to v0.8.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/61ffbb32a5c6f75a8d61f6f059fc9b39cfd7e5e7/bower.json#L38) has `angular-animate` listed in dependencies

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.8.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.8.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.8.2

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Comment by jivinivan** [comment]
We may want to re-release this as 0.9 or even 1.0 since there are some significant changes here.

**Comment by Chochek** [comment]
I thought about that but decide to go with 0.8.2 becasue even though there are a lot of new things here, there aren't any breaking changes. We could go with 0.9.0 if you think it would be better but I'd save the 1.0 for when we get everything we need for the new design and switch the styles completely.

**Comment by jivinivan** [comment]
Technically there are no breaking changes but the new modal and alert changes make it more of a minor release. http://semver.org/

I know we are only using it internally with strict versioning but I like to keep the mindset that someday we could release conventions to the world. In that case someone using a version such as `~0.8` wouldn't expect significant design changes from `0.8.1` to `0.8.2`.

We can leave this one as is but maybe we bump up to `0.9` on the next release.

**Comment by chaselee** [comment]
agree this should be 0.9 and 0.8.2 should be removed. then 0.9.x can probably house everything leading up to the finish of the new design elements, which can leave us at 1.0.x.

**Pull request merged**
