### PR TITLE
Release v0.5.2

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [ ] Show noItemsText when all items have chosen on a gaSelect follow up

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/0c04e9689643eeb05d290eb457b8acf968463c69/bower.json#L3) is updated to v0.5.2

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.5.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.5.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.5.2

**Comment by jivinivan** [comment]
@forgingdestiny please QA

**Comment by forgingdestiny** [comment]
:palm_tree:

**Pull request merged**
