### PR TITLE
Release v0.13.11

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
@jivinivan please reviwew

**Comment by jivinivan** [comment]
👍

**Comment by Chochek** [comment]
@jivinivan please QA
- [ ] - version is 0.13.11 in [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3)
- [ ] - release created - https://github.com/GetAmbassador/conventions-bower/releases
- [ ] - release created - https://github.com/GetAmbassador/ambassador-conventions/releases

**Comment by jivinivan** [comment]
🌴

**Pull request merged**
