### PR TITLE
Release v0.5.3

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- [x] Added NZD to gaCurrency

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/987c6c8d0c01ff51ee7974f04004ca54e8d50e0b/bower.json#L3) is updated to v0.5.3

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.5.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.5.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.5.3

**Comment by jivinivan** [comment]
@tplorts please QA

**Comment by tplorts** [comment]
QAing

**Comment by tplorts** [comment]
:palm_tree:

**Comment by tplorts** [comment]
@jivinivan I cannot update labels; please do so for me.

**Comment by jivinivan** [comment]
Updated thanks!

**Pull request merged**
