### PR TITLE
Release v0.8.1

### PR DESCRIPTION
**Pull request by jivinivan**
- [x] Use jsonp fallback for restangular GET requests when CORS ajax is not supported
- [x] Add manual spinner/loader on form fields

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/ee457c7a8c506ce4bd44cbb4c508c20a7862062d/bower.json#L3) is updated to v0.8.1

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.8.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.8.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.8.1

**Comment by jivinivan** [comment]
@chaselee please QA

**Comment by chaselee** [comment]
QAing

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
