### PR TITLE
Release v0.7.0

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Fixed: number comparing in the $diff service
- [x] Fixed: Display-per-page dropdown of table not always entirely visible
- [x] smart-table performance: getPinnedStyle
- [x] Slight visual distinction for pinned columns

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/d2275ba5e0022ab906283246c18e1a306bd637b5/bower.json#L3) is updated to v0.7.0

**Comment by jivinivan** [comment]
@tplorts please review

**Comment by tplorts** [comment]
reviewing

**Comment by tplorts** [comment]
:+1:

**Comment by jivinivan** [comment]
## Review Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.7.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.7.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.7.0

**Comment by jivinivan** [comment]
@brandoshmando please QA

**Comment by Chochek** [comment]
Got it :palm_tree:

**Pull request merged**
