### PR TITLE
Release v0.4.25

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- [ ] Fixed additional params on checkboxes

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/983a6d045fac170094be4369ebf8cf821b3a4afd/bower.json#L3) is updated to 0.4.25

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.25
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.25
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.25

**Comment by jivinivan** [comment]
@forgingdestiny please QA

**Comment by jivinivan** [comment]
@brandoshmando please QA

**Comment by brandoshmando** [comment]
:palm_tree:

**Pull request merged**
