### PR TITLE
Release v0.12.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Enable single selection mode in smart tables
- [x] Add the class for bordered tables

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/5e039b24170ed2c5cf4809b68fe839912944c988/bower.json#L3) has updated version v0.12.1

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.12.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.12.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.12.2

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
