### PR TITLE
Release v0.5.1

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Show noItemsText when all items have chosen on a gaSelect

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/424e6e008742f9de7286366d8275de6be5e9c7ed/bower.json#L3) is updated to v0.5.1

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by gpszymczak** [comment]
sorry, reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.5.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.5.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.5.1

**Comment by jivinivan** [comment]
@brandoshmando please QA

**Comment by chaselee** [comment]
QAing

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
