### PR TITLE
Release v0.10.4

### PR DESCRIPTION
**Pull request by Chochek**
- [x] Additional icon set
- [x] Close external ordering dropdown when an option is clicked
- [x] Add new notification style to alerts

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/09afee2969d95f622d29c7bec5715aacd39b7fd7/bower.json#L3) has updated version v0.10.4
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/09afee2969d95f622d29c7bec5715aacd39b7fd7/bower.json#L40) contains `ionicons`

**Comment by Chochek** [comment]
@gpszymczak please review spec

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.4
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.4
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.4

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
