### PR TITLE
Release v0.11.6

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- Ga-proportion-ring improvements

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/055673ec5003f54f21e3e5c286f34abd4fd0132c/bower.json#L3) has updated version v0.11.6

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.6
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.6
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.6

**Comment by jivinivan** [comment]
@briandavidson please QA

**Comment by briandavidson** [comment]
QA'ing

**Comment by briandavidson** [comment]
:moneybag:

**Pull request merged**
