### PR TITLE
Release v0.4.18

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Reduced full width responsive break point for modals
- [x] Ability to pass in auto font size multiplier on stat boxes
- [x] Ability to show spinner on manage actions

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/f37ff931d9d02a7af5ac7cd5d45e4f39add6f1db/bower.json#L3) is updated to 0.4.18

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.18
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.18
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.18

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
