### PR TITLE
Release v0.6.0

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- [ ] Field errors span the full width of the container

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/ba195fcdb131aa33d0cd1bea4dcfd8317aed0ba2/bower.json#L3) is updated to v0.6.0

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.6.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.6.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.6.0

**Comment by jivinivan** [comment]
@tplorts please QA

**Comment by jivinivan** [comment]
:palm_tree: (via @chaselee )

**Pull request merged**
