### PR TITLE
Release v0.11.8

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain:
- [x] Add filters and the search string to the TABLE_FINISHED_LOADING event data

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/9cb96a6684261b6c6f4471f2942cf6c506d7895e/bower.json#L3) has updated version v0.11.7

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.8
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.8
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.8

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
