### PR TITLE
Release v0.9.0

### PR DESCRIPTION
**Pull request by Chochek**
Re-release v0.8.2 as v0.9.0

### CODE REVIEW

**Comment by Chochek** [comment]
### Review plan
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/0daf22a9f66561962d3efb8aaa5ec5a6286ccdcd/bower.json#L3) has updated version v0.9.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/0daf22a9f66561962d3efb8aaa5ec5a6286ccdcd/bower.json#L24) has `"fontawesome": "~4.3.0"`

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.9.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.9.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.9.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L24) has `"fontawesome": "~4.3.0"`

**Comment by Chochek** [comment]
@chaselee please QA

**Comment by Chochek** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:palm_tree: :hamburger: :palm_tree:

**Pull request merged**
