### PR TITLE
Release v0.9.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain:
- [x] New style option for form fields
- [x] New style option for toggle switch
- [x] New style option for sliders
- [x] Set the "on" switch text font size to 9 px and weight to semibold

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/17e3c40b8d7d635c5d947c1fe9ed47641910ae3e/bower.json#L3) is updated to v0.9.2

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.9.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.9.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.9.2

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
