### PR TITLE
Release v0.11.9

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- Fixed negative time values showing in activity feed
- Show default actions on tables without selection checkboxes

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/3250e51e391dab41ec710ddf0ed75c7180d88474/bower.json#L3) has updated version v0.11.9
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/3250e51e391dab41ec710ddf0ed75c7180d88474/bower.json#L41) contains moment as a dependency `"moment": "~2.10.6"`

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.9
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.9
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) contains moment as a dependency `"moment": "~2.10.6"`
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.9

**Comment by jivinivan** [comment]
@briandavidson please QA

**Comment by briandavidson** [comment]
QA'ing

**Comment by briandavidson** [comment]
:moneybag:

**Pull request merged**
