### PR TITLE
Release v0.4.16

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [ ] Table search bar size adjustments

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/6eca756949abd508bb7db156d31287fbd2e055bd/bower.json#L3) is updated to 0.4.16

**Comment by jivinivan** [comment]
@gpszymczak please review

**Comment by chaselee** [comment]
:+1:

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.16
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.16
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.16

**Comment by jivinivan** [comment]
@chaselee please QA

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
:palm_tree:

**Pull request merged**
