### PR TITLE
Release v0.7.3

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [ ] Fix multi-line table headers in Safari
- [ ] Add param to show formatted value in tooltip on gaCurrency
- [ ] Required ga-select dropdown not being validated

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/78_release_v0_7_3/bower.json#L3) is updated to v0.7.3

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.7.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.7.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.7.3

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
