### PR TITLE
Release v0.10.13

### PR DESCRIPTION
**Pull request by jivinivan**
This release will contain:
- [ ] [#103092302] New modal design option
- [ ] [#103092436] Show icons and tooltips on small and extra small screens, otherwise show text on table action buttons

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/44be2d196357517707ba49f0bd8914a17b427834/bower.json#L3) has updated version v0.10.13
- [ ] angular-bootstrap is updated to 0.11.2 in [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/44be2d196357517707ba49f0bd8914a17b427834/bower.json#L25)

**Comment by jivinivan** [comment]
@Chochek please review.

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.13
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.13
- [ ] angular-bootstrap is updated to 0.11.2 in [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L25)
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.13

0 points

**Comment by jivinivan** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
