### PR TITLE
Release v0.11.3

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- Reset checked items when table is updated
- Go to previous page if no items after table update

### CODE REVIEW

**Comment by gpszymczak** [comment]
:+1:

**Comment by jivinivan** [comment]
### Review Plan

- [x] Code is updated
- [x] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/9e5d9634016603e36f7f8945159013cb1718a659/bower.json#L3) has updated version v0.11.3

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.3

**Comment by jivinivan** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
