### PR TITLE
Re-Release v0.6.2

### PR DESCRIPTION
**Pull request by jivinivan**

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by jivinivan** [comment]
@tplorts please review

**Comment by tplorts** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] conventions-bower 0.6.2 release date is today https://github.com/GetAmbassador/conventions-bower/releases
- [ ] ambassador-conventions 0.6.2 release date is today https://github.com/GetAmbassador/ambassador-conventions/releases

**Comment by jivinivan** [comment]
@tplorts please QA

**Comment by tplorts** [comment]
:palm_tree:

**Pull request merged**
