### PR TITLE
Re-release v0.10.9

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
### Review plan
- [ ] `ga-redactor.min.js` is updated

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan
- [ ] ambassador-conventions v0.10.9 release time is a few minutes ago (15 at the moment of writing) - https://github.com/GetAmbassador/conventions-bower/releases/tag/v0.10.9
- [ ] conventions-bower v0.10.9 release time is an hour ago - https://github.com/GetAmbassador/ambassador-conventions/releases/tag/v0.10.9

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
