### PR TITLE
Release v0.4.14

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] clickAnywhereButHere fix

### CODE REVIEW

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/21a0a9fb4ab6c47ca670a7fdef63c931696a21e3/bower.json#L3) is updated

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan
- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.14
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.14
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.14

**Comment by jivinivan** [comment]
Will merge as soon as https://github.com/GetAmbassador/ambassador-conventions/pull/222 is QA'd

**Comment by jivinivan** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
