### PR TITLE
Release v0.5.0

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] New gaSelect list format
- [x] Use parenthesis for negative point values in gaCurrecy

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/82339e327b4d0e5d35faf5f4d8d993144c25a7af/bower.json#L3) is updated to v0.5.0

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.5.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.5.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.5.0

**Comment by jivinivan** [comment]
@chaselee please QA

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
