### PR TITLE
Release v0.6.1

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [ ] Always center the table loader in the visible portion of the table
- [ ] Increase table search bar width
- [ ] Set default datepicker format to MM-DD-YYYY
- [ ] Add a datepicker field type to gaFormField
- [ ] Improve calendar layout in table filters
- [ ] Fix manual date entry on the datepicker table filter

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/5dfa240f598c213fbf87f09f357621477e586c77/bower.json#L3) is updated to v0.6.1

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by jivinivan** [comment]
Waiting on https://github.com/GetAmbassador/ambassador-conventions/issues/261

**Comment by Chochek** [comment]
@jivinivan GetAmbassador/ambassador-conventions#261 and GetAmbassador/ambassador-conventions#293 are merged

**Comment by Chochek** [comment]
@gpszymczak please review (plan is a few comments above)

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.6.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.6.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.6.1

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
