### PR TITLE
Release v0.6.3

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Smart-table performance: dropdown menu for manage actions
- [x] Reset page to 1 when updating tables with exposed data
- [x] Issue with $diff service comparing strings

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/959a2c28e8a46b34e6b2cde5fb06763b57207b77/bower.json#L3) is updated to v0.6.3

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.6.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.6.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.6.3

**Comment by jivinivan** [comment]
@tplorts please QA

**Comment by jivinivan** [comment]
Bump @tplorts

**Comment by jivinivan** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
