### PR TITLE
Release v0.4.19

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include:
- [x] Enhancement: Ability to pass in a custom tag with manage actions cell
- [x] Fix: Reduce break point where table pagination drops to a second row
- [x] Fix: Position filter dropdown relatively if it's the only dropdown

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/7fe80d6c9b182a1387c4587de1c6d1fcec957414/bower.json#L3) is updated to v0.4.19

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.19
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.19
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.19

**Comment by jivinivan** [comment]
@mkuchen please QA

**Comment by mkuchen** [comment]
QAing

**Comment by mkuchen** [comment]
:hamburger: :palm_tree:

**Pull request merged**
