### PR TITLE
Release v0.4.23

### PR DESCRIPTION
**Pull request by jivinivan**
This release will include: 
- [ ] A "no items" option on gaSelect filter types
- [ ] Option to search by only one property if gaSelect is a non-async typeahead

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/4ada6d568ac69a345417d001b614754f2996d5dc/bower.json#L3) is updated to 0.4.23

**Comment by jivinivan** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.23
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.23
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.23

**Comment by jivinivan** [comment]
@chaselee please QA

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
