### PR TITLE
Release v0.10.10

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Fix double quotes
- [x] Update checkbox design
- [x] Handle multiline checbox labels
- [x] Wrap table header in one div so we can easily add borders to it

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/9815db615c6995bfa6be490183131a7151d26827/bower.json#L3) has updated version v0.10.10

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.10
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.10
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.10

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
