### PR TITLE
Release v0.10.11

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] - [#101925184] Add target icon to Ambassador icon set
- [x] - [#102374304] Fix row selecting on smart tables

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/39e2f548c7fcfa46b9c3cdb9ae4a021f2d78ec1f/bower.json#L3) has updated version v0.10.11
- [ ] `ambassador-icons-font` files are [updated] (https://github.com/GetAmbassador/conventions-bower/commit/39e2f548c7fcfa46b9c3cdb9ae4a021f2d78ec1f)

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.11
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.11
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.11

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
