### PR TITLE
Release v0.6.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Enable datepicker field disabling
- [x] Fix field stacking when apply action is on but not filters
- [x] Add optional attributes to alert directive: action & compile
- [x] Smart tables don't get left margin when pinned
- [x] smartTable enhancements

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/70_release_v0_6_2/bower.json#L3) is updated to v0.6.2

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.6.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.6.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.6.2

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
