### PR TITLE
Release v0.12.1

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Remove min-width from table element
- [x] Improvements for the alert conventions in modals
- [x] Allow passing custom headers to $file.upload

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/26699f1b2afea25eab914c741e7f0354e8c4662c/bower.json#L3) has updated version v0.11.10

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.12.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.12.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.12.1

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
