### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Remove isolate scope from gaInfiniteScroll directive
- [x] gaSelect enhancements

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/bf316cb3b67d0cd8d51a05940ab759d0acf5d1a4/bower.json#L3) is updated to v0.8.0

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.8.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.8.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.8.0

**Comment by Chochek** [comment]
@tplorts please QA

**Comment by tplorts** [comment]
QAing

**Comment by tplorts** [comment]
:palm_tree:

**Pull request merged**
