### PR TITLE
Release v0.10.12

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain:
- [x] [#99948778] Adjust table sorting icons
- [x] [#102667104] Update button border radius
- [x] [#102677566] Table pinning not working properly in Safari
- [x] [#102462288] Set pinned row height dynamically

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/392625977e11f6b9a3d59f44758508d072eeb92b/bower.json#L3) has updated version v0.10.12

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.12
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.12
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.12

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
