### PR TITLE
Release v0.10.3

### PR DESCRIPTION
**Pull request by Chochek**
This release will contain
- [x] Handling multiple lines of text in buttons
- [x] Change binding for proportion ring "name"

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan
- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/2f5925b1f6c5513bdc5d8528b4a97d57d1113633/bower.json#L3) has updated version v0.10.3

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.10.3
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.10.3
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.10.3

**Comment by Chochek** [comment]
@briandavidson please QA

**Comment by briandavidson** [comment]
:palm_tree:

**Pull request merged**
