### PR TITLE
Re-Release v0.7.3

### PR DESCRIPTION
**Pull request by Chochek**
When https://github.com/GetAmbassador/ambassador-conventions/issues/345 is deployed

### CODE REVIEW

**Comment by Chochek** [comment]
### Review plan
- [ ] `components/ga-forms.min.js` and `ga-conventions.min.js` are updated

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA Plan

- [ ] conventions-bower 0.7.3 release date is today https://github.com/GetAmbassador/conventions-bower/releases
- [ ] ambassador-conventions 0.7.3 release date is yesterday https://github.com/GetAmbassador/ambassador-conventions/releases

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by jivinivan** [comment]
QAing

**Comment by jivinivan** [comment]
:palm_tree:

**Pull request merged**
