### PR TITLE
Release v0.9.4

### PR DESCRIPTION
**Pull request by jivinivan**
- [x] New snippet alert style

### CODE REVIEW

**Comment by jivinivan** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/e2a72934fb6d47ee177a8265bdac8f0f6762c043/bower.json#L3) has updated version v0.9.4

**Comment by jivinivan** [comment]
@chaselee please review

**Comment by chaselee** [comment]
:+1:

**Comment by jivinivan** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.9.4
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.9.4
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.9.4

**Comment by jivinivan** [comment]
@brandoshmando please QA

**Comment by brandoshmando** [comment]
QA'ing

**Comment by jivinivan** [comment]
@brandoshmando palm tree? :)

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
