### PR TITLE
Release v0.4.21

### PR DESCRIPTION
**Pull request by gpszymczak**
This release will include:
- [ ] Upgraded ngInfiniteScroll (so we don't need jQuery)
- [ ] Consistent number formats in gaCurrency directive

### CODE REVIEW

**Comment by gpszymczak** [comment]
### Review Plan

- [ ] Code is updated 
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/pull/59/files#diff-0a08a7565aba4405282251491979bb6bR3) is updated to 0.4.21

**Comment by gpszymczak** [comment]
@Chochek please review

**Comment by Chochek** [comment]
:+1:

**Comment by gpszymczak** [comment]
### QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.4.21
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.4.21
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.4.21

**Comment by gpszymczak** [comment]
@Chochek please QA

**Comment by Chochek** [comment]
:palm_tree:

**Pull request merged**
