### PR TITLE
Release v0.9.1

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Set `scroll` to true for `form` type alerts
- [x] Fix font smoothing on modal titles

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/1d85c87a3ccf047bb09f36c95eaf9f2628e201c8/bower.json#L3) is updated to v0.9.1

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.9.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.9.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.9.1

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
