### PR TITLE
Release v0.11.2

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] Add a button tooltip placement option
- [x] Update modal background color
- [x] Only add a promise to the promise keeper if one wasn't already added by the table or if it was added but resolved in the meantime

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [x] Code is updated
- [x] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/f05197945017f89f3f78fc50bef258107866620b/bower.json#L3) has updated version v0.11.2

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.2
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.2
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.2

**Comment by Chochek** [comment]
@briandavidson please QA

**Comment by briandavidson** [comment]
QA'ing

**Comment by briandavidson** [comment]
:trophy:

**Pull request merged**
