### PR TITLE
Re-release v0.10.13 as v0.11.0

### PR DESCRIPTION
**Pull request by Chochek**

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/49a756a590cb9acb0ee6f499791973997a550b1c/bower.json#L3) has updated version v0.11.0

**Comment by Chochek** [comment]
@gpszymczak please review

**Comment by gpszymczak** [comment]
reviewing

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.0
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.0
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.0

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing

**Comment by gpszymczak** [comment]
:palm_tree:

**Pull request merged**
