### PR TITLE
Release v0.7.1

### PR DESCRIPTION
**Pull request by Chochek**
This release will include:
- [x] remove invalid filter when error occurs
- [x] Filter out already selected values in non-async typeahead

### CODE REVIEW

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/b49ba155cc63b984afbf2a7469722c73b71b0b79/bower.json#L3) is updated to v0.7.1

**Comment by Chochek** [comment]
@tplorts please review

**Comment by tplorts** [comment]
reviewing

**Comment by tplorts** [comment]
:white_check_mark:

**Comment by Chochek** [comment]
## QA Plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.7.1
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.7.1
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.7.1

**Comment by Chochek** [comment]
@jivinivan please QA

**Comment by chaselee** [comment]
:palm_tree:

**Pull request merged**
